BINS = ['llvm-dlltool-12',
'lli-12',
'clang-rename-12',
'clang++-12',
'clang-include-fixer-12',
'clang-cl-12',
'llvm-profgen-12',
'llvm-split-12',
'verify-uselistorder-12',
'llvm-strip-12',
'clang-doc-12',
'clang-apply-replacements-12',
'llvm-PerfectShuffle-12',
'clang-scan-deps-12',
'scan-build-py-12',
'llvm-install-name-tool-12',
'llvm-ifs-12',
'clang-check-12',
'llvm-dwarfdump-12',
'sancov-12',
'llvm-rtdyld-12',
'llvm-reduce-12',
'llvm-pdbutil-12',
'llvm-cat-12',
'llvm-dwp-12',
'llvm-symbolizer-12',
'bugpoint-12',
'FileCheck-12',
'llvm-c-test-12',
'llvm-jitlink-12',
'hwasan_symbolize-12',
'llvm-bitcode-strip-12',
'llvm-tblgen-12',
'llvm-bcanalyzer-12',
'obj2yaml-12',
'llvm-mt-12',
'llvm-ar-12',
'llvm-as-12',
'clang-move-12',
'clang-refactor-12',
'llvm-rc-12',
'llvm-mc-12',
'llvm-nm-12',
'llvm-addr2line-12',
'clang-cpp-12',
'llvm-dis-12',
'dsymutil-12',
'llvm-lto2-12',
'not-12',
'llvm-exegesis-12',
'llvm-xray-12',
'llvm-undname-12',
'llvm-libtool-darwin-12',
'llvm-cvtres-12',
'llvm-ranlib-12',
'llvm-objdump-12',
'yaml-bench-12',
'llvm-elfabi-12',
'llvm-cxxdump-12',
'llvm-mca-12',
'modularize-12',
'clang-query-12',
'llvm-readobj-12',
'split-file-12',
'lli-child-target-12',
'llvm-diff-12',
'clang-extdef-mapping-12',
'hmaptool-12',
'llvm-readelf-12',
'llvm-size-12',
'llvm-profdata-12',
'llvm-link-12',
'pp-trace-12',
'llvm-config-12',
'sanstats-12',
'llvm-stress-12',
'llc-12',
'find-all-symbols-12',
'llvm-lipo-12',
'llvm-ml-12',
'llvm-cfi-verify-12',
'diagtool-12',
'llvm-modextract-12',
'llvm-cov-12',
'scan-build-12',
'clang-offload-wrapper-12',
'asan_symbolize-12',
'opt-12',
'scan-view-12',
'llvm-cxxfilt-12',
'llvm-gsymutil-12',
'llvm-opt-report-12',
'llvm-lto-12',
'llvm-cxxmap-12',
'count-12',
'clang-offload-bundler-12',
'llvm-objcopy-12',
'llvm-extract-12',
'c-index-test-12',
'llvm-lib-12',
'llvm-strings-12',
'clang-change-namespace-12',
'clang-reorder-fields-12',
'llvm-jitlink-executor-12',
'yaml2obj-12']

cmd = ['update-alternatives', '--force', '--install', '/usr/local/bin/clang', 'clang', '/usr/bin/clang-12', '100']
for bin in BINS:
    cmd += ['--slave', f'/usr/local/bin/{bin[:-3]}', bin, f'/usr/bin/{bin}']

import subprocess as sp

sp.run(cmd, check=True)

sp.run(['ln', '-sf', 'libLLVM-12.so', 'libLLVM.so'], check=True, cwd='/usr/lib/x86_64-linux-gnu')
sp.run(['ln', '-sf', 'libclang-12.so', 'libclang.so'], check=True, cwd='/usr/lib/x86_64-linux-gnu')
sp.run(['ln', '-sf', 'libclang-cpp12.so', 'libclang-cpp.so'], check=True, cwd='/usr/lib/x86_64-linux-gnu')